
linters:
  presets:
    - bugs
    - comment
    - error
    - format
    - import
    - metalinter
    - module
    - performance
    - style
    - test
    - unused

  disable:
    - revive

run:
  skip-dirs:
    - example
    - tests
